### ISSUE TITLE
Styles for a blog are not applied to the /read display page.

### ISSUE THREAD

**Issue by rouilj** [writefreely/writefreely#608]
### Describe the bug
I have added the following styles to the css for my blog:

```css
img[title^=Banner] {
    display: block;
    height: 204px;
    object-fit: cover;
    object-position: 0 -20px;
    padding-block-end: 1em;
    width: 96%;
}

.preview img[title^=Banner] {
    display: block;
    height: 120px;
    object-fit: cover;
    object-position: 0 -20px;
    padding-block-end: 1em;
    width: 96%;
}

.preview:has(p>img) {max-height: 360px;}

.preview:has(p>img) .over {
    top: calc(5em + 120px);
}
```
The intent is to show an image at the top of a post titled "Banner image" limited to a specific size.
The first css block is inserted into the page and works when displaying the post.

The rest of the css is meant to make the banner image shorter and to expand the space available for the summary by:

  * showing a shorter section of the banner image
  * changing the preview size to 360px and
  * shifting the gradient overlay that fades out the text at the bottom of the summary by the height of the image

These work when I apply them manually using the developer tools in the browser.
However they are not inserted in the /read page. Trying to use the style generation in the collection template
```
 {{if .StyleSheet}}<style type="text/css">{{.StyleSheetDisplay}}</style>{{end}}
```
or the collection-post template
```
{{if .Collection.StyleSheet}}<style type="text/css">{{.Collection.StyleSheetDisplay}}</style>{{end}}
```
causes a traceback from writefreely. It looks like .Collection or .StyleSheet are not defined.

### Steps to reproduce (if necessary)
1. Insert a banner image on a post with an `img` tag just after the title using a `title="Banner image"` attribute
2. Add the css above to the blog's css from the setting screen
3. View the post from the blog summary and see the added css in the browsers dev tools.
4. Navigate to the `/read` url path and see just he banner image as the image is large enough to take up 100% of the size of the summary 

### Expected behavior
I expected the css to be included on all pages of the writefreely instance.

### Application configuration
 - **Single mode or Multi-user mode?** Multi
 - **Database?** sqlite
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**: 0.13.2

p.s. As I was writing this up,  realized that the css needs to be modified so that `has(p > img)` is `has(p > img[title^=Banner])`, but that doesn't affect the problem report.
