### ISSUE TITLE
Logging in after initial setup/config  - "User doesn't exist"

### ISSUE THREAD

**Issue by don-ferris** [writefreely/writefreely#994]
Running docker image using docker-compose (shown below) then executing `writefreely --config` I get "User doesn't exist" when attempting to login using the username and password that I _just created_ using `writefreely --config`

**Single mode** 
**Database: sqlite?**
**No open registration?**
**Federation disabled?**

**Version**: Whatever gets pulled in the docker-compose file

My docker-compose file:
```
services:
  write-freely:
    image: nephatrine/write-freely:latest
    container_name: write-freely
    environment:
      TZ: America/Los_Angeles
      PUID: 1000
      PGID: 1000
    ports:
      - "70:70/tcp"       # REPLACE WITH [##]:70/tcp
      - "8080:8080/tcp"   # REPLACE WITH [2##80]:8080/tcp
    volumes:
      - .wfconfig:/mnt/config
```
